export const casesSeedData = [
  {
    id: 'toolbox',
    name: 'Toolbox Case',
    price: 12.0,
    image: '/yellow-toolbox-case-csgo.jpg',
    description: 'Caixa contendo skins raras de armas',
    skins: [
      { name: 'Black Tie', weapon: 'XM1014', rarity: 'rare', chance: 0.017, image: '/black-tie-xm1014.jpg' },
      { name: 'Phobos', weapon: 'AWP', rarity: 'epic', chance: 0.002, image: '/phobos-awp.jpg' },
      { name: 'Light Box', weapon: 'MAC-10', rarity: 'uncommon', chance: 0.008, image: '/light-box-mac10.jpg' },
      { name: 'Phantom', weapon: 'P250', rarity: 'rare', chance: 0.015, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Kitbash', weapon: 'MP5-SD', rarity: 'epic', chance: 0.006, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Moto Gloves Eclipse', weapon: 'Gloves', rarity: 'legendary', chance: 0.001, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Falchion Knife Autotronic', weapon: 'Knife', rarity: 'legendary', chance: 0.002, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Fuel Injector', weapon: 'AK-47', rarity: 'epic', chance: 0.008, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Hand Wraps Duct Tape', weapon: 'Gloves', rarity: 'legendary', chance: 0.003, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Survival Knife Case Hardened', weapon: 'Knife', rarity: 'legendary', chance: 0.001, image: '/placeholder.svg?height=150&width=200' },
      { name: 'USP-S Orion', weapon: 'USP-S', rarity: 'rare', chance: 0.048, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Asiimov', weapon: 'AWP', rarity: 'epic', chance: 0.004, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'daily',
    name: 'Daily Case',
    price: 0,
    image: '/blue-daily-case-csgo.jpg',
    description: 'Caixa gratuita diária',
    skins: [
      { name: 'P250 Sand Dune', weapon: 'P250', rarity: 'common', chance: 0.5, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Glock-18 Night', weapon: 'Glock-18', rarity: 'common', chance: 0.3, image: '/placeholder.svg?height=150&width=200' },
      { name: 'M4A4 Desert Storm', weapon: 'M4A4', rarity: 'uncommon', chance: 0.15, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Safari Mesh', weapon: 'AK-47', rarity: 'uncommon', chance: 0.05, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'low',
    name: 'Low Case',
    price: 1.8,
    image: '/yellow-low-case-csgo.jpg',
    description: 'Caixa básica com skins comuns',
    skins: [
      { name: 'MP9 Sand Dashed', weapon: 'MP9', rarity: 'common', chance: 0.4, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Nova Walnut', weapon: 'Nova', rarity: 'common', chance: 0.35, image: '/placeholder.svg?height=150&width=200' },
      { name: 'P90 Sand Spray', weapon: 'P90', rarity: 'uncommon', chance: 0.2, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Galil AR Sage Spray', weapon: 'Galil AR', rarity: 'uncommon', chance: 0.05, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'indirect',
    name: 'Indirect Case',
    price: 3.0,
    image: '/green-indirect-case-csgo.jpg',
    description: 'Caixa com skins de qualidade média',
    skins: [
      { name: 'M4A1-S Boreal Forest', weapon: 'M4A1-S', rarity: 'uncommon', chance: 0.3, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Jungle Spray', weapon: 'AK-47', rarity: 'uncommon', chance: 0.25, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Worm God', weapon: 'AWP', rarity: 'rare', chance: 0.15, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Desert Eagle Mudder', weapon: 'Desert Eagle', rarity: 'rare', chance: 0.2, image: '/placeholder.svg?height=150&width=200' },
      { name: 'USP-S Forest Leaves', weapon: 'USP-S', rarity: 'uncommon', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'medium',
    name: 'Medium Case',
    price: 4.5,
    image: '/blue-medium-case-csgo.jpg',
    description: 'Caixa com skins raras',
    skins: [
      { name: 'M4A4 Radiation Hazard', weapon: 'M4A4', rarity: 'rare', chance: 0.25, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Blue Laminate', weapon: 'AK-47', rarity: 'rare', chance: 0.2, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Electric Hive', weapon: 'AWP', rarity: 'epic', chance: 0.15, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Glock-18 Water Elemental', weapon: 'Glock-18', rarity: 'rare', chance: 0.25, image: '/placeholder.svg?height=150&width=200' },
      { name: 'P250 Undertow', weapon: 'P250', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Karambit Blue Steel', weapon: 'Knife', rarity: 'legendary', chance: 0.05, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'ultra',
    name: 'Ultra Case',
    price: 6.0,
    image: '/red-ultra-case-csgo.jpg',
    description: 'Caixa premium com skins épicas',
    skins: [
      { name: 'M4A4 Howl', weapon: 'M4A4', rarity: 'legendary', chance: 0.01, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Fire Serpent', weapon: 'AK-47', rarity: 'legendary', chance: 0.015, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Dragon Lore', weapon: 'AWP', rarity: 'legendary', chance: 0.005, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Desert Eagle Blaze', weapon: 'Desert Eagle', rarity: 'epic', chance: 0.08, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Glock-18 Fade', weapon: 'Glock-18', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Karambit Fade', weapon: 'Knife', rarity: 'legendary', chance: 0.02, image: '/placeholder.svg?height=150&width=200' },
      { name: "Sport Gloves Pandora's Box", weapon: 'Gloves', rarity: 'legendary', chance: 0.025, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'ammo',
    name: 'Ammo Case',
    price: 6.3,
    image: '/green-ammo-case-csgo.jpg',
    description: 'Caixa militar com skins táticas',
    skins: [
      { name: 'M4A1-S Cyrex', weapon: 'M4A1-S', rarity: 'epic', chance: 0.12, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Vulcan', weapon: 'AK-47', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Corticera', weapon: 'AWP', rarity: 'rare', chance: 0.2, image: '/placeholder.svg?height=150&width=200' },
      { name: 'P90 Asiimov', weapon: 'P90', rarity: 'epic', chance: 0.15, image: '/placeholder.svg?height=150&width=200' },
      { name: 'USP-S Caiman', weapon: 'USP-S', rarity: 'rare', chance: 0.25, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Butterfly Knife Slaughter', weapon: 'Knife', rarity: 'legendary', chance: 0.03, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'rust',
    name: 'Rust Case',
    price: 6.6,
    image: '/rust-case-csgo.jpg',
    description: 'Caixa enferrujada com skins vintage',
    skins: [
      { name: 'AK-47 Redline', weapon: 'AK-47', rarity: 'epic', chance: 0.15, image: '/placeholder.svg?height=150&width=200' },
      { name: 'M4A4 Asiimov', weapon: 'M4A4', rarity: 'epic', chance: 0.12, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Redline', weapon: 'AWP', rarity: 'rare', chance: 0.2, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Desert Eagle Crimson Web', weapon: 'Desert Eagle', rarity: 'rare', chance: 0.18, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Glock-18 Twilight Galaxy', weapon: 'Glock-18', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Bayonet Rust Coat', weapon: 'Knife', rarity: 'legendary', chance: 0.05, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'c4',
    name: 'C4 Case',
    price: 7.2,
    image: '/c4-case-csgo.jpg',
    description: 'Caixa explosiva com skins poderosas',
    skins: [
      { name: 'M4A1-S Hyper Beast', weapon: 'M4A1-S', rarity: 'epic', chance: 0.13, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Neon Revolution', weapon: 'AK-47', rarity: 'epic', chance: 0.11, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Hyper Beast', weapon: 'AWP', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'P250 Nuclear Threat', weapon: 'P250', rarity: 'rare', chance: 0.2, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Five-SeveN Hyper Beast', weapon: 'Five-SeveN', rarity: 'rare', chance: 0.22, image: '/placeholder.svg?height=150&width=200' },
      { name: 'M9 Bayonet Doppler', weapon: 'Knife', rarity: 'legendary', chance: 0.04, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'chocolate',
    name: 'Chocolate Case',
    price: 8.4,
    image: '/chocolate-case-csgo.jpg',
    description: 'Caixa doce com skins premium',
    skins: [
      { name: 'M4A4 The Emperor', weapon: 'M4A4', rarity: 'epic', chance: 0.12, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 The Empress', weapon: 'AK-47', rarity: 'epic', chance: 0.11, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Neo-Noir', weapon: 'AWP', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Desert Eagle Kumicho Dragon', weapon: 'Desert Eagle', rarity: 'rare', chance: 0.18, image: '/placeholder.svg?height=150&width=200' },
      { name: 'USP-S Kill Confirmed', weapon: 'USP-S', rarity: 'epic', chance: 0.13, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Karambit Tiger Tooth', weapon: 'Knife', rarity: 'legendary', chance: 0.06, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'ember',
    name: 'Ember Case',
    price: 9.0,
    image: '/ember-case-csgo-orange.jpg',
    description: 'Caixa flamejante com skins lendárias',
    skins: [
      { name: 'M4A4 Poseidon', weapon: 'M4A4', rarity: 'legendary', chance: 0.02, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 Wild Lotus', weapon: 'AK-47', rarity: 'legendary', chance: 0.018, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Medusa', weapon: 'AWP', rarity: 'legendary', chance: 0.015, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Desert Eagle Golden Koi', weapon: 'Desert Eagle', rarity: 'epic', chance: 0.12, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Glock-18 Gamma Doppler', weapon: 'Glock-18', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Karambit Gamma Doppler', weapon: 'Knife', rarity: 'legendary', chance: 0.035, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Driver Gloves Crimson Weave', weapon: 'Gloves', rarity: 'legendary', chance: 0.04, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
  {
    id: 'neon',
    name: 'Neon Case',
    price: 12.0,
    image: '/neon-case-csgo-purple.jpg',
    description: 'Caixa neon com as melhores skins',
    skins: [
      { name: 'M4A4 Temukau', weapon: 'M4A4', rarity: 'legendary', chance: 0.025, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AK-47 X-Ray', weapon: 'AK-47', rarity: 'epic', chance: 0.1, image: '/placeholder.svg?height=150&width=200' },
      { name: 'AWP Chromatic Aberration', weapon: 'AWP', rarity: 'epic', chance: 0.09, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Desert Eagle Printstream', weapon: 'Desert Eagle', rarity: 'epic', chance: 0.11, image: '/placeholder.svg?height=150&width=200' },
      { name: 'USP-S Printstream', weapon: 'USP-S', rarity: 'epic', chance: 0.12, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Butterfly Knife Gamma Doppler', weapon: 'Knife', rarity: 'legendary', chance: 0.03, image: '/placeholder.svg?height=150&width=200' },
      { name: 'Specialist Gloves Fade', weapon: 'Gloves', rarity: 'legendary', chance: 0.035, image: '/placeholder.svg?height=150&width=200' },
    ],
  },
];

